Repository TomaLeleux/Casa-de-camel, pull requests merged in 2018-05, with the labels that each got.

#11 Feature/routes
  app/controllers/bookings_controller.rb
  app/controllers/camels_controller.rb
  app/controllers/profile_controller.rb
  app/views/profile/dashboard.html.erb
  app/views/profile/show.html.erb
  config/routes.rb
  test/controllers/profile_controller_test.rb
Labels: enhancement

#22 Add price_per_day to camel model #14
  db/migrate/20180529084707_add_price_per_day_to_camels.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement

#41 should work with the js file in app/javascript/components #17
  app/javascript/components/card.js
  app/javascript/packs/application.js
Labels: component

#56 Bug/model validation
  app/models/booking.rb
  app/models/camel.rb
  app/models/user.rb
Labels: :camel: bug :dromedary_camel:

#58 Add Geocoder, api key, display map in Camel/index #53
  Gemfile
  Gemfile.lock
  app/controllers/camels_controller.rb
  app/javascript/packs/map.js
  app/models/camel.rb
  app/views/camels/index.html.erb
  app/views/layouts/application.html.erb
  config/initializers/geocoder.rb
  db/migrate/20180530094756_add_coordinates_to_camels.rb
  db/migrate/20180530095042_add_address_to_camels.rb
  db/schema.rb
  package.json
  yarn.lock
Labels: :dromedary_camel: enhancement :camel:

#79 Booking is now editable for both ends
  app/controllers/bookings_controller.rb
  app/policies/booking_policy.rb
  app/views/bookings/edit.html.erb
  app/views/bookings/index.html.erb
  app/views/profile/dashboard.html.erb
  config/routes.rb
Labels: :dromedary_camel: enhancement :camel:
